# Generated by Django 4.2.3 on 2024-01-19 17:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0002_product_is_sale_product_sale_price'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='Category',
            new_name='category',
        ),
    ]
